server:
  port: 12780
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: Log@gmc+
    url: jdbc:h2:file:./loga
    username: loga

  jpa:
    hibernate:
    ddl-auto: update
    properties:
      hibernate:

  mail:
    host: localhost
    port: 12725
    username: loga
    password: secret

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000